name = "lean-iap"
version = "0.1.0"
defaultTargets = ["lean-iap"]

[leanOptions]
pp.unicode.fun = true # pretty-prints `fun a â†¦ b`

[[require]]
name = "mathlib"
scope = "leanprover-community"
rev = "v4.27.0-rc1"
